[package]
name = "twitch_api"
version = "0.1.2"
edition = "2018"
authors = ["Matt Shanker <hatmatteroffact@gmail.com>"]
description = "Twitch API library"
repository = "https://github.com/hatmatter/twitch_api"
readme = "README.md"
keywords = ["twitch", "api"]
categories = ["api-bindings"]
license = "Apache-2.0"

[dependencies]
chrono = { version = "0.3", features = ["serde", "rustc-serialize"] }
hyper = "0.10.4"
hyper-rustls = "0.6.0"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
urlparse = "0.7.3"