name: Rust (build)

on: 
  pull_request:
    branches:
    - feature-dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose